# dev 환경  postgres
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
    # data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # 시작 할때 h2에 있는 테이블 데이터를 삭제 후 다시 생성하는 옵션
  h2: # local h2 db 사용시..
    console:
      enabled: true
      path: /console # h2 콘솔 주소 - localhost:8080/console
logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR