# prod 환경  postgres
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://112.166.159.199:53306/task?characterEncoding=UTF-8&serverTimezone=UTC
      username: task
      password: Task!234
      poolName: HikariCP
      connection-test-query : SELECT NOW() FROM dual
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none # 시작 할때 h2에 있는 테이블 데이터를 삭제 후 다시 생성하는 옵션
    generate-ddl: true
    database: mysql
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: INFO
    org.hibernate: ERROR
